### ISSUE TITLE
Unite the 3 versions of this repo

### ISSUE THREAD

**Issue by PedroHLC** [desiderantes/sdl2_vapi#1]
I initially wrote this binding in my avalanche repo, than txasatonga appeared binded the remaining sdl2 extensions and convinced me to move development to a new repo he created on gitorious, I accepted and developed through a fork with merge request, then he accidentally forced a push and I could no longer keep merging, today there is 3 different versions of the same project (mine on gitorious and mirrored here, txasatonga on gitourious and yours here). We have to consider unite them in one and delete the others so than forks be born of the active developed one. As contributor, your opinion is needed.

**Comment by desiderantes** [comment]
Well, since this is reaching completion, I think it should be merged to provide a complete binding
